/*
 * Filename: swc_brakelight_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_brakelight_control
 * shortname: brakelight_control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brakelight_control.h"



/* USER CODE START SWC_BRAKELIGHT_CONTROL_INCLUDE */

/* USER CODE END SWC_BRAKELIGHT_CONTROL_INCLUDE */


#include "sp_signalpool.h"

/* USER CODE START SWC_BRAKELIGHT_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_CONTROL_USERDEFINITIONS */



/*
 * component: swc_brakelight_control
 * cycletime: 100
 * description: Runnable
 * events: ev_controlspeed_onData
 * name: BRAKELIGHT_CONTROL_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: 
 * signalOUT: 
 * task: 
 */
void BRAKELIGHT_CONTROL_setBrakeLight_run(RTE_event ev){
	
	/* USER CODE START BRAKELIGHT_CONTROL_setBrakeLight_run */

    /* USER CODE END BRAKELIGHT_CONTROL_setBrakeLight_run */
}

/* USER CODE START SWC_BRAKELIGHT_CONTROL_FUNCTIONS */

/* USER CODE END SWC_BRAKELIGHT_CONTROL_FUNCTIONS */

