
/*
 * Filename: swc_calc_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component
 */

#ifndef _H_DEFINE_SWC_CALC_CONTROL
#define _H_DEFINE_SWC_CALC_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"   
#include "watchdog.h"
/* USER CODE START SWC_CALC_CONTROL_INCLUDES */

/* USER CODE END SWC_CALC_CONTROL_INCLUDES */



/* USER CODE START SWC_CALC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CALC_CONTROL_USERDEFINITIONS */


/*
 * component: swc_calc_control
 * cycletime: 0
 * description: Runnable
 * events: ev_joystick_onData
 * name: CALC_CONTROL_Calccontrol_calcControl_run
 * shortname: Calccontrol_calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_Control
 */
void CALC_CONTROL_Calccontrol_calcControl_run(RTE_event ev);


#endif