
/*
 * Filename: swc_joystick.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component
 */

#ifndef _H_DEFINE_SWC_JOYSTICK
#define _H_DEFINE_SWC_JOYSTICK

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_JOYSTICK_INCLUDES */

/* USER CODE END SWC_JOYSTICK_INCLUDES */



/* USER CODE START SWC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SWC_JOYSTICK_USERDEFINITIONS */


/*
 * component: swc_joystick
 * cycletime: 100
 * description: Runnable
 * events: ev_10ms
 * name: JOYSTICK_Joystick_readJoystick_run
 * shortname: Joystick_readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: 
 */
void JOYSTICK_Joystick_readJoystick_run(RTE_event ev);


#endif