
/*
 * Filename: swc_engine_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component
 */

#ifndef _H_DEFINE_SWC_ENGINE_CONTROL
#define _H_DEFINE_SWC_ENGINE_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_ENGINE_CONTROL_INCLUDES */

/* USER CODE END SWC_ENGINE_CONTROL_INCLUDES */



/* USER CODE START SWC_ENGINE_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_CONTROL_USERDEFINITIONS */


/*
 * component: swc_engine_control
 * cycletime: 100
 * description: Runnable
 * events: ev_100ms
 * name: ENGINE_CONTROL_Engine_Control_setEngine_run
 * shortname: Engine_Control_setEngine
 * signalIN: 
 * signalOUT: 
 * task: 
 */
void ENGINE_CONTROL_Engine_Control_setEngine_run(RTE_event ev);


#endif