
/*
 * Filename: swc_brakelight_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component
 */

#ifndef _H_DEFINE_SWC_BRAKELIGHT_CONTROL
#define _H_DEFINE_SWC_BRAKELIGHT_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_BRAKELIGHT_CONTROL_INCLUDES */

/* USER CODE END SWC_BRAKELIGHT_CONTROL_INCLUDES */



/* USER CODE START SWC_BRAKELIGHT_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_CONTROL_USERDEFINITIONS */


/*
 * component: swc_brakelight_control
 * cycletime: 100
 * description: Runnable
 * events: ev_controlspeed_onData
 * name: BRAKELIGHT_CONTROL_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: 
 * signalOUT: 
 * task: 
 */
void BRAKELIGHT_CONTROL_setBrakeLight_run(RTE_event ev);


#endif