/*
 * Filename: tsk_io.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task having runnables which either receives input from the user or provide output to the actuators. Running runnables in 10ms and 100ms.
 * events: ev_100ms|ev_10ms|ev_joystick_onData
 * mode: Event
 * name: tsk_IO
 * shortname: IO
 * signalpoolsRO: 
 * signalpoolsRW: 
 * tickEvent: 0
 * timertickperiod: 1
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_io.h"



/* USER CODE START TSK_IO_INCLUDE */

/* USER CODE END TSK_IO_INCLUDE */




/* USER CODE START TSK_IO_USERDEFINITIONS */

/* USER CODE END TSK_IO_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_io[] = {
}; 
const uint16_t RTE_eventActivation_tsk_io_size = sizeof (RTE_eventActivationTable_tsk_io) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task having runnables which either receives input from the user or provide output to the actuators. Running runnables in 10ms and 100ms.
 * events: ev_100ms|ev_10ms|ev_joystick_onData
 * mode: Event
 * name: tsk_IO
 * shortname: IO
 * signalpoolsRO: 
 * signalpoolsRW: 
 * tickEvent: 0
 * timertickperiod: 1
 */
TASK(tsk_io)
{
    EventMaskType ev = 0;
    
	/* USER CODE START TSK_IO_INIT */

	/* USER CODE END TSK_IO_INIT */
	
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_100ms|ev_10ms|ev_joystick_onData);
        GetEvent(tsk_io,&ev);
        ClearEvent(ev);
		
		/* USER CODE START TSK_IO_TASKBODY_PRE */

		/* USER CODE END TSK_IO_TASKBODY_PRE */
    

        //Process Event table on event
        RTE_ProcessEventTable(RTE_eventActivationTable_tsk_io, RTE_eventActivation_tsk_io_size, ev);
		
		/* USER CODE START TSK_IO_TASKBODY_POST */

		/* USER CODE END TSK_IO_TASKBODY_POST */

        
    }
	
	//Just in Case
	TerminateTask();
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_IO_ISR */

/* USER CODE END TSK_IO_ISR */

