/*
 * Filename: tsk_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task doing work
 * events: ev_controlspeed_onData
 * mode: Event
 * name: tsk_Brakelight
 * shortname: Brakelight
 * signalpoolsRO: sp_signalPool
 * signalpoolsRW: sp_signalPool
 * tickEvent: 0
 * timertickperiod: 0
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_brakelight.h"



/* USER CODE START TSK_BRAKELIGHT_INCLUDE */

/* USER CODE END TSK_BRAKELIGHT_INCLUDE */

#include "swc_brakelight_control.h"



/* USER CODE START TSK_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END TSK_BRAKELIGHT_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_brakelight[] = {
    { BRAKELIGHT_CONTROL_setBrakeLight_run, ev_controlspeed_onData },  //Runnable
}; 
const uint16_t RTE_eventActivation_tsk_brakelight_size = sizeof (RTE_eventActivationTable_tsk_brakelight) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task doing work
 * events: ev_controlspeed_onData
 * mode: Event
 * name: tsk_Brakelight
 * shortname: Brakelight
 * signalpoolsRO: sp_signalPool
 * signalpoolsRW: sp_signalPool
 * tickEvent: 0
 * timertickperiod: 0
 */
TASK(tsk_Brakelight)
{
    EventMaskType ev = 0;
    
	/* USER CODE START TSK_BRAKELIGHT_INIT */

	/* USER CODE END TSK_BRAKELIGHT_INIT */
	
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_controlspeed_onData);
        GetEvent(tsk_Brakelight,&ev);
        ClearEvent(ev);
		
		/* USER CODE START TSK_BRAKELIGHT_TASKBODY_PRE */

		/* USER CODE END TSK_BRAKELIGHT_TASKBODY_PRE */
    

        //Process Event table on event
        RTE_ProcessEventTable(RTE_eventActivationTable_tsk_brakelight, RTE_eventActivation_tsk_brakelight_size, ev);
		
		/* USER CODE START TSK_BRAKELIGHT_TASKBODY_POST */

		/* USER CODE END TSK_BRAKELIGHT_TASKBODY_POST */

        
    }
	
	//Just in Case
	TerminateTask();
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_BRAKELIGHT_ISR */

/* USER CODE END TSK_BRAKELIGHT_ISR */

