
/*
 * Filename: tsk_brakelight.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Task doing work
 */

#ifndef _H_DEFINE_TSK_BRAKELIGHT
#define _H_DEFINE_TSK_BRAKELIGHT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_BRAKELIGHT_INCLUDES */

/* USER CODE END TSK_BRAKELIGHT_INCLUDES */



/*
 * description: Task doing work
 * events: ev_controlspeed_onData
 * mode: Event
 * name: tsk_Brakelight
 * shortname: Brakelight
 * signalpoolsRO: sp_signalPool
 * signalpoolsRW: sp_signalPool
 * tickEvent: 0
 * timertickperiod: 0
 */
DeclareTask(tsk_brakelight);

/* USER CODE START TSK_BRAKELIGHT_TASKUSERFUNCTION */

/* USER CODE END TSK_BRAKELIGHT_TASKUSERFUNCTION */


#endif