/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_ee.h"
#include "ErikaOS_ee_tracing.h"
#include "JOYSTICK_ADC_XY.h"
#include "Joystick_Horizontal_aliases.h"
#include "Joystick_Horizontal.h"
#include "Joystick_Vertical_aliases.h"
#include "Joystick_Vertical.h"
#include "UART_LOG.h"
#include "greenled_aliases.h"
#include "greenled.h"
#include "MasterClck.h"
#include "RGB_PWM_green.h"
#include "redLED_aliases.h"
#include "redLED.h"
#include "JOYSTICK_ADC_XY_SAR.h"
#include "JOYSTICK_ADC_XY_IntClock.h"
#include "JOYSTICK_ADC_XY_TempBuf_dma.h"
#include "JOYSTICK_ADC_XY_FinalBuf_dma.h"
#include "JOYSTICK_ADC_XY_IRQ.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

