
/*
 * Filename: sp_signalpool.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: 
 */

#ifndef _H_DEFINE_SP_SIGNALPOOL
#define _H_DEFINE_SP_SIGNALPOOL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_SIGNALPOOL_INCLUDES */

/* USER CODE END SP_SIGNALPOOL_INCLUDES */



#include "sc_speed.h"
#include "sc_joystick.h"



/*
 * description: SO speed value forwarded to engine and brakelight
 * indriver: default
 * name: so_speed
 * onDataError: 0
 * onDataUpdate: ev_controlspeed_onData
 * outdriver: 0
 * resource: None
 * shortname: speed
 * signalclass: sc_speed
 * signalpool: sp_signalPool
 */
extern SC_SPEED_t SO_SPEED_signal;


/*
 * description: SO for transmitting joystick data between SWCs
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_joystick_onData
 * outdriver: default
 * resource: None
 * shortname: joystick
 * signalclass: sc_joystick
 * signalpool: sp_signalPool
 */
extern SC_JOYSTICK_t SO_JOYSTICK_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_signalpool_tick(uint32_t tick);

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_signalpool();

#endif